server.port=8020
bakery.url=http://bakery:
bakery.port=8010

spring.kafka.bootstrap-servers=kafka0:9092,kafka1:9092,kafka2:9092
kafka.server=kafka0:9092,kafka1:9092,kafka2:9092
spring.kafka.consumer.group-id=CG1
kafka.consumer.group.id=CG1