server.port=8020
bakery.url=http://localhost:
bakery.port=8010

spring.kafka.bootstrap-servers=localhost:9094,localhost:9095,localhost:9096
kafka.server=localhost:9094,localhost:9095,localhost:9096
#kafka.topic.name=Kasa1
spring.kafka.consumer.group-id=CG1
kafka.consumer.group.id=CG1