spring.application.name=bakery
spring.datasource.url=jdbc:postgresql://localhost:5555/bakerydb
spring.datasource.username=foo
spring.datasource.password=bar
spring.sql.init.continue-on-error=true
spring.kafka.bootstrap-servers=localhost:9094,localhost:9095,localhost:9096
kafka.server=localhost:9094,localhost:9095,localhost:9096
spring.kafka.consumer.group-id=CG1
kafka.consumer.group.id=CG1