spring.application.name=bakery
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
server.port=8010
spring.kafka.bootstrap-servers=localhost:9094,localhost:9095,localhost:9096
kafka.server=localhost:9094,localhost:9095,localhost:9096
spring.kafka.consumer.group-id=CG1
kafka.consumer.group.id=CG1