services:
  buns:
    container_name: buns_app
    build:
      context: ../
      dockerfile: infrastructure/buns_store/service/Dockerfile
    ports:
      - 8060:8020

  bakery_db:
    container_name: db_app
    build:
      context: ./bakery_service/database
      dockerfile: Dockerfile
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}

  bakery:
    container_name: bakery_app
    build:
      context: ../
      dockerfile: infrastructure/bakery_service/service/Dockerfile
    ports:
      - 8070:8010
    environment:
      - DATABASE_PORT=5432
      - DATABASE_NAME=bakerydb
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_HOST=bakery_db
    depends_on:
      - bakery_db