name: bakery
on:
  pull_request:
    paths:
      - "*"
jobs:
  bakery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup JDK 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Build with Gradle"
        run: ./gradlew build