name: bakery
on:
  pull_request:
    branches: [ "main" ]
jobs:
  bakery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Gradle permisions"
        run: chmod +x ./gradlew
      - name: "pwd"
        run: pwd
      - name: "ll"
        run: ls -al
      - name: "Build with Gradle"
        run: ./gradlew build